plugins {
    id 'application'
    id 'org.openjfx.javafxplugin' version '0.1.0'
    id 'com.gradleup.shadow' version '9.5.1'
}

group = 'dev.genyo.installer'
version = '2.1.2'

repositories {
    mavenCentral()
}

def javafxVersion = '21.0.2'

dependencies {
    testImplementation platform('org.junit:junit-bom:6.0.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'

    runtimeOnly "org.openjfx:javafx-graphics:${javafxVersion}:win"
    runtimeOnly "org.openjfx:javafx-graphics:${javafxVersion}:mac"
    runtimeOnly "org.openjfx:javafx-graphics:${javafxVersion}:linux"
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(26)
    }
}

application {
    mainClass = 'dev.genyo.installer.Main'
}

javafx {
    version = javafxVersion
    modules = ['javafx.controls', 'javafx.graphics']
}

tasks.named('jar') {
    archiveClassifier.set('all')
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
    manifest {
        attributes(
                'Main-Class': 'dev.genyo.installer.Main'
        )
    }
}

test {
    useJUnitPlatform()
}